apiVersion: v1
kind: Namespace
metadata:
 name: myns
 labels: 
  dept: engineering
---
# Write deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: fortune-deploy
 namespace: myns
 labels:
  dept: engineering
  app: fortune
spec:
 replicas: 3
 selector:
  matchLabels:
   app: fortune-pod
 template:
  #pod's yaml. Apiversion for pod is decided by deployment's
  metadata: 
   name: fortune-pod
   labels:
    dept: engineering
    app: fortune-pod
  spec:
   containers:
   - name: fortune-containers
     image: chukmunnlee/fortune:v1
     imagePullPolicy: IfNotPresent
     ports:
     - name: http-port
       containerPort: 3000



